# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks:
  - command: bashbox build --install

vscode:
  extensions:
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
